---
version: '3'
services:
  nats-a:
    container_name: n1
    image: nats:2.10.10
    entrypoint: /nats-server
    command:
      - -c=./nats-server.conf
#      - -D # enable debugging output
    networks:
      - nats
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./jetstream-cluster/n1:/data
      - ./nats-server-host-a.conf:/nats-server.conf

  nats-b:
    container_name: n2
    image: nats:2.10.10
    entrypoint: /nats-server
    command:
      - -c=./nats-server.conf
#      - -D # enable debugging output
    networks:
      - nats
    ports:
      - 4223:4222
      - 8223:8222
    volumes:
      - ./jetstream-cluster/n2:/data
      - ./nats-server-host-b.conf:/nats-server.conf

  nats-c:
    container_name: n3
    image: nats:2.10.10
    entrypoint: /nats-server
    command:
      - -c=./nats-server.conf
#      - -D # enable debugging output
    networks:
      - nats
    ports:
      - 4224:4222
      - 8224:8222
    volumes:
      - ./jetstream-cluster/n3:/data
      - ./nats-server-host-c.conf:/nats-server.conf

  nats-d:
    container_name: n4
    image: nats:2.10.10
    entrypoint: /nats-server
    command:
      - -c=./nats-server.conf
#      - -D # enable debugging output
    networks:
      - nats
    ports:
      - 4225:4222
      - 8225:8222
    volumes:
      - ./jetstream-cluster/n4:/data
      - ./nats-server-host-d.conf:/nats-server.conf

  pub:
    build: .
    command: [ "./pubsub", "publish" ]
    networks:
      - nats
    environment:
      - NATS_URL=nats://nats-a:4222,nats://nats-b:4223,nats://nats-c:4224
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  sub:
    build: .
    command: [ "./pubsub", "subscribe" ]
    networks:
      - nats
    environment:
      - NATS_URL=nats://nats-a:4222,nats://nats-b:4222,nats://nats-c:4222
    depends_on:
      - nats-a
      - nats-b
      - nats-c

networks:
  nats: {}
