version: '3'
services:
 
  nats:
    image: nats:2.10.10
    container_name: 'nats-server'
    restart: on-failure
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    hostname: nats-server
    command:
      - -js # enable JetStream functionality
      - -D # enable debugging output
  
  pub:
    build: .
    command: [ "./pubsub", "publish" ]
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  sub:
    build: .
    command: [ "./pubsub", "subscribe" ]
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
